# Generated by Django 3.0 on 2019-12-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191211_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='seeders',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
